version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres_skeleton_sample
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DATABASE: skeleton_sample
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "65432:65432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    command:
      -p 65432
volumes:
  pgdata: